# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_rest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fgrpc_rest.proto\"\x1e\n\x06\x61\x64\x64Msg\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x1a\n\x0brawImageMsg\x12\x0b\n\x03img\x18\x01 \x01(\x0c\"%\n\rdotProductMsg\x12\t\n\x01\x61\x18\x01 \x03(\x02\x12\t\n\x01\x62\x18\x02 \x03(\x02\"\x1b\n\x0cjsonImageMsg\x12\x0b\n\x03img\x18\x01 \x01(\t\"\x17\n\x08\x61\x64\x64Reply\x12\x0b\n\x03sum\x18\x01 \x01(\x05\"%\n\x0f\x64otProductReply\x12\x12\n\ndotproduct\x18\x01 \x01(\x02\"+\n\nimageReply\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x32\xcd\x01\n\tGrpc_lab6\x12\"\n\nPerformAdd\x12\x07.addMsg\x1a\t.addReply\"\x00\x12.\n\x0fImageDimensions\x12\x0c.rawImageMsg\x1a\x0b.imageReply\"\x00\x12\x37\n\x11PerformDotProduct\x12\x0e.dotProductMsg\x1a\x10.dotProductReply\"\x00\x12\x33\n\x13JsonImageDimensions\x12\r.jsonImageMsg\x1a\x0b.imageReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_rest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADDMSG._serialized_start=19
  _ADDMSG._serialized_end=49
  _RAWIMAGEMSG._serialized_start=51
  _RAWIMAGEMSG._serialized_end=77
  _DOTPRODUCTMSG._serialized_start=79
  _DOTPRODUCTMSG._serialized_end=116
  _JSONIMAGEMSG._serialized_start=118
  _JSONIMAGEMSG._serialized_end=145
  _ADDREPLY._serialized_start=147
  _ADDREPLY._serialized_end=170
  _DOTPRODUCTREPLY._serialized_start=172
  _DOTPRODUCTREPLY._serialized_end=209
  _IMAGEREPLY._serialized_start=211
  _IMAGEREPLY._serialized_end=254
  _GRPC_LAB6._serialized_start=257
  _GRPC_LAB6._serialized_end=462
# @@protoc_insertion_point(module_scope)
